### ISSUE TITLE
Sourcing issue meesage

### ISSUE THREAD

**Issue by RDaneelOlivav** [RobotecAI/ros2-for-unity#8]
Hi,

I'm getting the following error:

![Screenshot from 2021-08-27 18-52-58](https://user-images.githubusercontent.com/4933774/131162216-9cd0e5c6-cba5-410c-9990-fbdf0baaec15.png)

Whats the procedure to launch unity sourced?
Because I sourced the ros env and launched the unity editor from the same terminal.
I don't know if it's because I hade created that UnityProject in a Unity session without sourcing?

Any ideas?

**Comment by adamdbrw** [comment]
I will look into it, thank you for raising this up

**Comment by adamdbrw** [comment]
How many ROS2UnityComponent objects do you have in your scripts? I recommend treating it as a singleton:

/// TODO: this is meant to be used as a one-of (a singleton). Enforce. However, things should work
/// anyway with more than one since the underlying library can handle multiple init and shutdown calls,

If you look into the class it is meant for handling all the ros2 nodes and executables.

**Comment by adamdbrw** [comment]
@RDaneelOlivav is the problem still there? If so, could you share your logs. We tried but were not able to reproduce the crash on your Unity version.

**Comment by adamdbrw** [comment]
@RDaneelOlivav a friendly bump

**Comment by adamdbrw** [comment]
I am closing this issue (not reproducible, major Unity version back from our target, no response from issue author)
